<%= chart :bar %>
  <%=component :chart_border %>
    left_thickness: 2
    
  <%=component :chart_grid_h %>
    thickness: 1
  
  <%=component :chart_grid_v %>
    thickness: 5    

  <%=component :chart_rect %>
    height: <%=@options[:graph_options][:barchartheight]%> 
    y:      <%=@options[:graph_options][:barcharty]%>
