<%= chart :pie %>

  <%=component :chart_label %>
    position: inside
    separator: ','
    color: ffffff
    
<% if @options[:graph_options][:decimals] %>
    decimals: <%=@options[:graph_options][:decimals]%>
<% end %>

  <%=component :chart_rect %>
    x:         <%=@options[:graph_options][:piechartx]%>
    y:         <%=@options[:graph_options][:piecharty]%>

  <%=component :chart_border %>
    left_thickness:   0
    bottom_thickness: 0
    top_thickness:    0
    right_thickness:  0

  <%=component :chart_grid_h %>
    alpha:     0

  <%=component :chart_grid_v %>
    alpha:     0

  <%=component :series_explode %>
    number: 0

  <%=component :filter %>
    filters:
      - <%= filter_type :bevel %>
          id:               bevel_data
          angle:            0
          blurX:            0
          blurY:            0
          distance:         1
          highlightAlpha:   90
          highlightColor:   ffffff
          shadowColor:      ffffff
          shadowAlpha:      1
          type:             full
