---
base:
  adapter: postgresql
  encoding: utf8
  username: root
  pool: 1
  wait_timeout: 5
  min_messages: warning
development:
  adapter: postgresql
  username: root
  database: vmdb_production
  encoding: utf8
  pool: 1
  wait_timeout: 5
  min_messages: warning
  host: cfme-db.cloud.ebpi.nl
  password: v2:{12qRa2RkMQfKMKyemSMZ2g==}
production:
  adapter: postgresql
  username: root
  database: vmdb_production
  encoding: utf8
  pool: 1
  wait_timeout: 5
  min_messages: warning
  host: cfme-db.cloud.ebpi.nl
  password: v2:{12qRa2RkMQfKMKyemSMZ2g==}
test:
  adapter: postgresql
  encoding: utf8
  username: root
  pool: 3
  wait_timeout: 5
  min_messages: warning
  database: vmdb_test
